# Generated by Django 5.1.4 on 2024-12-13 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='edit_time',
            field=models.DateTimeField(blank=True, help_text='task is edited at'),
        ),
    ]
